spring:
  application:
    name: border-service
  cloud:
    discovery:
      enabled: true
      client:
        composite-indicator:
          enabled: true            
  
  main:
    banner-mode: "off"
    
server:
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
eureka:
  server: 
    enable-self-preservation: false
  instance:
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

zuul:
  ignored-services: '*'
  prefix: /app
  routes:
    producer:
      service-id: etl-producer
      path: /producer/**
      
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000  
  eureka:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    